const products = [
  { id: 1, name: "Wireless Mouse", description: "A smooth and responsive wireless mouse", price: 299, image: "wireless_mouse.jpg" },
  { id: 2, name: "Bluetooth Headphones", description: "High quality over-ear Bluetooth headphones", price: 799, image: "bluetooth_headphones.jpg" },
  { id: 3, name: "Keyboard", description: "Mechanical backlit keyboard for productivity", price: 599, image: "keyboard.jpg" },
  { id: 4, name: "Charger Adapter", description: "Fast charging adapter for all your devices", price: 399, image: "charger.jpg" },
  { id: 5, name: "Apple iPhone", description: "Latest model with advanced features and performance", price: 59900, image: "apple_iphone.jpg" },
  { id: 6, name: "HP Laptop", description: "Lightweight and powerful laptop for everyday use", price: 46490, image: "hp_laptop.jpg" },
  { id: 7, name: "Apple iPad", description: "Sleek and portable tablet for entertainment and work", price: 35900, image: "apple_ipad.jpg" },
  { id: 8, name: "Apple Smartwatch", description: "Stay connected and fit with this stylish smartwatch", price: 49900, image: "apple_smartwatch.jpg" },
  { id: 9, name: "Summer Style T-Shirt", description: "Comfortable cotton t-shirt with a modern summer look", price: 499, image: "summer_stylish_tshirt.jpg" },
  { id: 10, name: "Football Boots", description: "Durable and stylish boots for soccer lovers", price: 2999, image: "football_boots.jpg" },
  { id: 11, name: "Football", description: "Premium quality football for training and matches", price: 799, image: "football.jpg" },
  { id: 12, name: "Trending Jeans", description: "Stylish jeans perfect for casual wear", price: 1499, image: "trending_jeans.jpg" },
  { id: 13, name: "Boys Caps", description: "Cool caps for boys with adjustable fit", price: 299, image: "boys_caps.jpg" },
  { id: 14, name: "Voltas AC", description: "Energy-efficient air conditioner with fast cooling", price: 49999, image: "voltas_ac.jpg" },
  { id: 15, name: "Cricket Test Ball", description: "Professional leather cricket ball for test matches", price: 799, image: "cricket_testball.jpg" },
  { id: 16, name: "Dry Fruits Mix", description: "Healthy and delicious assorted dry fruits", price: 599, image: "dryfruits_mix.jpg" },
  { id: 17, name: "Orange Tank Juice Powder", description: "Instant orange drink powder for refreshment", price: 199, image: "orange_tankjuicepowder.jpg" },
  { id: 18, name: "Colgate Toothpaste", description: "Popular toothpaste for strong teeth and fresh breath", price: 99, image: "colgate_paste.jpg" },
  { id: 19, name: "Gillette Shaver", description: "Smooth and clean shave with precision blades", price: 799, image: "gillette_shaver.jpg" },
  { id: 20, name: "Bluesteel Bottle", description: "Reusable water bottle for hydration on the go", price: 499, image: "bluesteel_bottle.jpg" },
  { id: 21, name: "Racer Gloves", description: "Durable gloves designed for bike racing", price: 799, image: "racer_gloves.jpg" },
  { id: 22, name: "Bike Helmet", description: "Safety helmet for bike rides and motorsports", price: 2999, image: "bike_helmet.jpg" },
  { id: 23, name: "Cool Glasses", description: "Trendy sunglasses with UV protection", price: 799, image: "cool_glasses.jpg" },
  { id: 24, name: "20,000mAh Power Bank", description: "High-capacity power bank to charge devices on the go", price: 1499, image: "20000mah_powerbank.jpg" },
  { id: 25, name: "Mountain Cycle", description: "Off-road mountain bike with durable frame", price: 24999, image: "mountain_cycle.jpg" },
  { id: 26, name: "MRF Cricket Bat", description: "High-quality cricket bat endorsed by pros", price: 5999, image: "mrf_cricketbat.jpg" },
  { id: 27, name: "Samsung Type-C Cable", description: "Fast charging and data cable for USB-C devices", price: 399, image: "samsung_c_cable.jpg" },
  { id: 28, name: "OnePlus AirPods", description: "Wireless earbuds with immersive sound experience", price: 4999, image: "oneplus_airpods.jpg" },
  { id: 29, name: "Crompton Air Cooler", description: "Powerful air cooler for efficient cooling in summer", price: 7999, image: "crompton_aircooler.jpg" },
  { id: 30, name: "Bajaj Iron Box", description: "Non-stick soleplate iron box for effortless ironing", price: 1299, image: "bajaj_ironbox.jpg" }
];

export default products;